"""
Connector: Gmail
Status: Active (Native)
Uses the local token.json generated by auth_gmail.py to read unread emails directly,
replacing the need for n8n.
"""

import base64
import email as email_lib
import os
import sys
from typing import Any, Dict, List

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from email_processor import IncomingEmail

# Paths relative to backend root
TOKEN_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "token.json")
SCOPES = [
    "https://www.googleapis.com/auth/gmail.modify",
    "https://www.googleapis.com/auth/gmail.send",
]


def is_configured() -> bool:
    """Returns True if the OAuth token is present and valid."""
    return os.path.exists(TOKEN_FILE)


def _get_gmail_service():
    """Builds and returns the Gmail API service object, refreshing the token if needed."""
    if not is_configured():
        return None

    try:
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

        if creds.expired and creds.refresh_token:
            from google.auth.transport.requests import Request
            creds.refresh(Request())
            # Persist the refreshed token so the next call doesn't need to refresh again
            with open(TOKEN_FILE, "w") as f:
                f.write(creds.to_json())

        service = build("gmail", "v1", credentials=creds)
        return service
    except Exception as e:
        print(f"Error building Gmail service: {e}")
        return None


LABEL_NAME = "marimba-processed"

# How many characters of each earlier thread message we feed to triage. A reply
# only needs enough of the prior turn to resolve what it points at ("agendarlo"
# → the meeting proposed before); the full history would just cost tokens.
THREAD_CONTEXT_CHARS = 1500


def _extract_body(payload: Dict[str, Any]) -> str:
    """
    Walk a Gmail message payload and return the best plain-text body we can find.

    Gmail can deliver simple single-part messages or multipart trees (text/plain
    + text/html + attachments). We prefer text/plain; if none exists we fall
    back to text/html stripped to bare text. Returns "" if nothing usable.
    """
    import re

    def _decode(data: str) -> str:
        try:
            return base64.urlsafe_b64decode(data.encode("ASCII")).decode("utf-8", errors="replace")
        except Exception:
            return ""

    def _walk(node: Dict[str, Any]) -> tuple[str, str]:
        """Returns (plain_text, html_text) found anywhere in this node."""
        plain, html = "", ""
        mime = node.get("mimeType", "")
        body = node.get("body", {})
        data = body.get("data")
        if data:
            decoded = _decode(data)
            if mime == "text/plain":
                plain += decoded
            elif mime == "text/html":
                html += decoded
        for part in node.get("parts", []) or []:
            p, h = _walk(part)
            plain += p
            html += h
        return plain, html

    plain, html = _walk(payload or {})
    if plain.strip():
        return plain.strip()
    if html.strip():
        # crude HTML → text fallback (good enough for replying with context)
        stripped = re.sub(r"<[^>]+>", "", html)
        stripped = re.sub(r"\s+\n", "\n", stripped)
        return stripped.strip()
    return ""


def _fetch_thread_context(service, thread_id: str, current_message_id: str) -> str:
    """
    For a reply, return a compact transcript of the EARLIER messages in its
    thread so triage can resolve what the reply leaves implicit. "¿puedes
    agendarlo?" only means something against the meeting proposed earlier in the
    conversation — without that prior turn the model reads the reply blind, sees
    a one-clause ask wrapped in pleasantries, and is liable to drop it.

    Returns "" when there's no prior context. Best-effort: a thread fetch must
    never break a sync, so any failure yields "" and the email is triaged on its
    own (exactly the previous behaviour).
    """
    if not thread_id:
        return ""
    try:
        thread = (
            service.users()
            .threads()
            .get(userId="me", id=thread_id, format="full")
            .execute()
        )
    except Exception as error:
        print(f"[Gmail Connector] Could not fetch thread {thread_id}: {error}")
        return ""

    messages = thread.get("messages", [])
    # Gmail returns thread messages in chronological order, so everything up to
    # the message we're triaging is prior context. Stop at it — we never want to
    # feed the model the reply itself back as "context".
    prior = []
    found_current = False
    for message in messages:
        if message.get("id") == current_message_id:
            found_current = True
            break
        prior.append(message)
    # If we never located the message we're triaging, we can't tell which turns
    # actually precede it — bail rather than risk feeding the reply back as its
    # own "earlier context".
    if not found_current or not prior:
        return ""

    # The two most recent prior turns carry almost all the referent value; older
    # turns rarely change the classification and just spend tokens.
    parts: list[str] = []
    for message in prior[-2:]:
        headers = message.get("payload", {}).get("headers", [])
        sender = next(
            (h["value"] for h in headers if h["name"].lower() == "from"), ""
        )
        body = _extract_body(message.get("payload", {}))
        excerpt = (body or message.get("snippet", "")).strip().replace("\n", " ")
        parts.append(f"From {sender}: {excerpt[:THREAD_CONTEXT_CHARS]}")
    return "\n".join(parts)


def get_or_create_label(service) -> str:
    """Finds the 'marimba-processed' label ID, or creates it if it doesn't exist."""
    results = service.users().labels().list(userId="me").execute()
    labels = results.get("labels", [])
    for label in labels:
        if label["name"] == LABEL_NAME:
            return label["id"]

    # Create it if not found
    label_object = {
        "name": LABEL_NAME,
        "labelListVisibility": "labelShow",
        "messageListVisibility": "show",
        "color": {
            "backgroundColor": "#ffad46",  # Amber color
            "textColor": "#000000",
        },
    }
    created_label = (
        service.users().labels().create(userId="me", body=label_object).execute()
    )
    return created_label["id"]


def fetch_unread_emails() -> List[IncomingEmail]:
    """
    Fetches emails from the last 5 days that haven't been processed by Marimba yet.
    Formats them exactly as n8n used to, so email_processor.py can naturally parse them.
    As soon as they are fetched, they are labeled 'marimba-processed' in Gmail.
    """
    service = _get_gmail_service()
    if not service:
        return []

    try:
        label_id = get_or_create_label(service)

        # 1. Fetch messages in inbox not yet processed by Marimba from the last 5 days
        query = f"in:inbox -label:{LABEL_NAME} newer_than:5d"
        results = service.users().messages().list(userId="me", q=query).execute()
        messages = results.get("messages", [])

        if not messages:
            return []

        parsed_emails = []
        messages_to_label = []

        # 2. Fetch full message details for each ID
        for msg in messages:
            msg_id = msg["id"]
            message_detail = (
                service.users()
                .messages()
                .get(userId="me", id=msg_id, format="full")
                .execute()
            )

            headers = message_detail["payload"].get("headers", [])
            subject = next(
                (h["value"] for h in headers if h["name"] == "Subject"), "No Subject"
            )
            sender = next(
                (h["value"] for h in headers if h["name"] == "From"), "Unknown Sender"
            )
            recipient = next((h["value"] for h in headers if h["name"] == "To"), "")
            # Cc is optional — most emails don't have it. We store it as the
            # raw header (e.g. "Alice <a@x.com>, Bob <b@y.com>") and parse
            # into clean addresses at API response time, matching how From/To
            # are handled. RFC permits multiple Cc headers; join them.
            cc_raw = ", ".join(
                h["value"] for h in headers if h["name"].lower() == "cc"
            )
            # RFC822 Message-ID — the canonical id used for In-Reply-To / References
            # so replies thread inside the original Gmail conversation.
            rfc822_id = next(
                (h["value"] for h in headers if h["name"].lower() == "message-id"), ""
            )

            snippet = message_detail.get("snippet", "")
            body = _extract_body(message_detail.get("payload", {}))

            # Replies and forwards often carry an ask whose referent lives
            # earlier in the thread ("agendarlo" → the meeting proposed before).
            # Only these need prior context, so we gate the extra thread fetch on
            # the Re:/Fwd: subject prefix rather than calling it for every email.
            thread_id = message_detail.get("threadId", msg_id)
            thread_context = ""
            # Cover both locales' prefixes — Spanish Gmail uses "RE:" for replies
            # and "RV:" for forwards, English uses "Re:"/"Fwd:"/"Fw:".
            subject_prefix = subject.lower().strip()
            if subject_prefix.startswith(("re:", "fwd:", "fw:", "rv:")):
                thread_context = _fetch_thread_context(service, thread_id, msg_id)

            incoming_email_data = {
                "id": msg_id,
                "threadId": thread_id,
                "snippet": snippet,
                "body": body,
                "thread_context": thread_context,
                "rfc822_message_id": rfc822_id,
                "internalDate": message_detail.get("internalDate", "0"),
                "Subject": subject,
                "From": sender,
                "To": recipient,
                "Cc": cc_raw,
                "payload": {
                    "mimeType": message_detail["payload"].get("mimeType", "text/plain")
                },
                "labels": [],
            }

            try:
                validated_email = IncomingEmail(**incoming_email_data)
                parsed_emails.append(validated_email)
                messages_to_label.append(msg_id)
            except Exception as e:
                print(f"Error parsing email {msg_id}: {e}")

        # 3. Label all successfully fetched emails as 'marimba-processed'
        if messages_to_label:
            service.users().messages().batchModify(
                userId="me",
                body={
                    "ids": messages_to_label,
                    "addLabelIds": [label_id],
                    # We no longer remove 'UNREAD' here, so you maintain your personal unread status!
                },
            ).execute()
            print(
                f"[Gmail Connector] Fetched and tagged {len(messages_to_label)} emails as '{LABEL_NAME}'."
            )

        return parsed_emails

    except HttpError as error:
        print(f"An error occurred pulling emails: {error}")
        return []


def mark_emails_read(message_ids: List[str]) -> int:
    """
    Clear the UNREAD flag on the given messages so they stop showing as bold /
    counting toward the teacher's unread total in Gmail.

    Non-destructive on purpose: we ONLY remove the system 'UNREAD' label. The
    emails stay in the inbox with every other label intact (including the amber
    'marimba-processed' tag), so nothing disappears and everything Marimba has
    touched is still findable. This is the "turn down the volume, don't delete"
    move — used for absence emails on sync and for action emails the moment the
    teacher dismisses them in the app.

    Best-effort: returns the count submitted, or 0 if Gmail isn't configured or
    the call failed. Never raises — marking-read must never break the action
    (sync or dismiss) that triggered it.
    """
    ids = [m for m in message_ids if m]
    if not ids:
        return 0

    service = _get_gmail_service()
    if not service:
        return 0

    try:
        service.users().messages().batchModify(
            userId="me",
            body={"ids": ids, "removeLabelIds": ["UNREAD"]},
        ).execute()
        print(f"[Gmail Connector] Marked {len(ids)} email(s) as read.")
        return len(ids)
    except Exception as error:
        print(f"[Gmail Connector] Error marking {len(ids)} email(s) read: {error}")
        return 0


def send_email(to: str, subject: str, body: str, cc: str | None = None) -> bool:
    """
    Send an email from the authenticated Gmail account.

    Args:
        to: Recipient email address
        subject: Email subject line
        body: Plain-text email body
        cc: Optional comma-separated CC addresses

    Returns:
        True if sent successfully, False otherwise
    """
    service = _get_gmail_service()
    if not service:
        return False

    try:
        message = email_lib.message.EmailMessage()
        message["To"] = to
        if cc:
            message["Cc"] = cc
        message["Subject"] = subject
        message.set_content(body)

        encoded = base64.urlsafe_b64encode(message.as_bytes()).decode()
        service.users().messages().send(
            userId="me", body={"raw": encoded}
        ).execute()
        return True

    except Exception as error:
        print(f"[Gmail Connector] Error sending email: {error}")
        return False


def send_email_with_attachments(
    *,
    to: str,
    subject: str,
    body: str,
    cc: str | None = None,
    attachments: list[Dict[str, Any]] | None = None,
) -> bool:
    """
    Send a freeform email with optional attachments.

    Args:
        to: comma-separated recipient list ("a@x.com, b@y.com").
        subject, body: as usual.
        cc: optional comma-separated CC list.
        attachments: list of {"filename": str, "mime_type": str, "data": bytes}.
            data is raw bytes; we base64-encode internally for the MIME envelope.

    Returns True on success. When attachments is None or empty, this is a
    multipart/alternative or plain message just like the simple send_email().
    """
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText
    from email.mime.base import MIMEBase
    from email import encoders

    service = _get_gmail_service()
    if not service:
        return False

    try:
        if attachments:
            msg = MIMEMultipart()
            msg["To"] = to
            if cc:
                msg["Cc"] = cc
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain", "utf-8"))
            for att in attachments:
                part = MIMEBase(*(att["mime_type"].split("/", 1) if "/" in att["mime_type"]
                                  else ("application", "octet-stream")))
                part.set_payload(att["data"])
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition",
                    f'attachment; filename="{att["filename"]}"',
                )
                msg.attach(part)
            raw_message = msg.as_bytes()
        else:
            # No attachments — same EmailMessage path as send_email().
            msg = email_lib.message.EmailMessage()
            msg["To"] = to
            if cc:
                msg["Cc"] = cc
            msg["Subject"] = subject
            msg.set_content(body)
            raw_message = msg.as_bytes()

        encoded = base64.urlsafe_b64encode(raw_message).decode()
        service.users().messages().send(
            userId="me", body={"raw": encoded}
        ).execute()
        return True

    except Exception as error:
        print(f"[Gmail Connector] Error sending email with attachments: {error}")
        return False


def create_draft(to: str | None, subject: str, body: str, cc: str | None = None) -> bool:
    """Save a new (non-threaded) email as a Gmail draft."""
    service = _get_gmail_service()
    if not service:
        return False
    try:
        message = email_lib.message.EmailMessage()
        if to:
            message["To"] = to
        if cc:
            message["Cc"] = cc
        message["Subject"] = subject
        message.set_content(body)
        encoded = base64.urlsafe_b64encode(message.as_bytes()).decode()
        service.users().drafts().create(
            userId="me", body={"message": {"raw": encoded}}
        ).execute()
        return True
    except Exception as error:
        print(f"[Gmail Connector] Error creating draft: {error}")
        return False


def create_draft_reply(
    *,
    to: str,
    subject: str,
    body: str,
    in_reply_to_rfc822_id: str,
    thread_id: str | None,
    cc: str | None = None,
) -> bool:
    """Save a threaded reply as a Gmail draft (same threading headers as send_reply)."""
    service = _get_gmail_service()
    if not service:
        return False
    if not subject.lower().startswith("re:"):
        subject = f"Re: {subject}"
    try:
        message = email_lib.message.EmailMessage()
        message["To"] = to
        if cc:
            message["Cc"] = cc
        message["Subject"] = subject
        if in_reply_to_rfc822_id:
            message["In-Reply-To"] = in_reply_to_rfc822_id
            message["References"] = in_reply_to_rfc822_id
        message.set_content(body)
        encoded = base64.urlsafe_b64encode(message.as_bytes()).decode()
        msg_payload: Dict[str, Any] = {"raw": encoded}
        if thread_id:
            msg_payload["threadId"] = thread_id
        service.users().drafts().create(
            userId="me", body={"message": msg_payload}
        ).execute()
        return True
    except Exception as error:
        print(f"[Gmail Connector] Error creating draft reply: {error}")
        return False


def send_reply(
    *,
    to: str,
    subject: str,
    body: str,
    in_reply_to_rfc822_id: str,
    thread_id: str | None,
    cc: str | None = None,
) -> bool:
    """
    Send a threaded reply. The message lands inside the same Gmail
    conversation as the original on both sender's and recipient's sides.

    Threading is achieved by:
      - Setting In-Reply-To and References to the RFC822 Message-ID of the
        message being replied to (RFC 2822 standard — the mail client uses
        this to group messages into threads).
      - Passing threadId in the Gmail API send payload so Gmail itself
        keeps it inside the originating thread on our account.

    Subject is normalised to "Re: ..." if not already prefixed.

    cc is optional — only included when the teacher explicitly opted in to
    "reply all" (excluded by default to avoid accidental over-sharing).
    """
    service = _get_gmail_service()
    if not service:
        return False

    if not subject.lower().startswith("re:"):
        subject = f"Re: {subject}"

    try:
        message = email_lib.message.EmailMessage()
        message["To"] = to
        if cc:
            message["Cc"] = cc
        message["Subject"] = subject
        if in_reply_to_rfc822_id:
            message["In-Reply-To"] = in_reply_to_rfc822_id
            message["References"] = in_reply_to_rfc822_id
        message.set_content(body)

        encoded = base64.urlsafe_b64encode(message.as_bytes()).decode()
        payload: Dict[str, Any] = {"raw": encoded}
        if thread_id:
            payload["threadId"] = thread_id

        service.users().messages().send(userId="me", body=payload).execute()
        return True

    except Exception as error:
        print(f"[Gmail Connector] Error sending threaded reply: {error}")
        return False


def _search_emails(query: str, limit: int) -> List[Dict[str, Any]]:
    """
    Internal: run a Gmail search and fetch the full body of each match.
    Returns a list of dicts the chat tool can hand directly to Mistral.

    `query` should already include scope (e.g. "in:sent newer_than:90d ...")
    so callers control the search surface explicitly.
    """
    service = _get_gmail_service()
    if not service:
        return []

    try:
        results = (
            service.users()
            .messages()
            .list(userId="me", q=query, maxResults=max(1, min(limit, 20)))
            .execute()
        )
        msg_ids = [m["id"] for m in results.get("messages", [])][:limit]

        out: List[Dict[str, Any]] = []
        for mid in msg_ids:
            detail = (
                service.users()
                .messages()
                .get(userId="me", id=mid, format="full")
                .execute()
            )
            headers = detail["payload"].get("headers", [])
            def _h(name: str) -> str:
                return next(
                    (h["value"] for h in headers if h["name"].lower() == name.lower()),
                    "",
                )
            body = _extract_body(detail.get("payload", {}))
            # Internal date is unix ms — convert to a readable ISO string
            try:
                from datetime import datetime as _dt, timezone as _tz
                iso = _dt.fromtimestamp(
                    int(detail.get("internalDate", "0")) / 1000, tz=_tz.utc
                ).isoformat()
            except Exception:
                iso = ""
            out.append({
                "id": mid,
                "thread_id": detail.get("threadId", mid),
                "subject": _h("Subject") or "(no subject)",
                "from": _h("From"),
                "to": _h("To"),
                "date": iso,
                # Truncate body so tool results stay token-bounded — Mistral
                # rarely needs more than ~2k chars to understand context.
                "body": (body or detail.get("snippet", ""))[:2000],
            })
        return out
    except HttpError as error:
        print(f"[Gmail search] HTTP error: {error}")
        return []
    except Exception as error:
        print(f"[Gmail search] Unexpected error: {error}")
        return []


def search_sent_emails(query: str, limit: int = 5) -> List[Dict[str, Any]]:
    """
    Search the teacher's sent mail from the last 90 days.

    `query` is a free-text Gmail search clause; we prepend the scope.
    Gmail's search is forgiving — both "Microsoft visit" and "subject:gira"
    work. 90-day window is a tradeoff: faster API responses, less context
    bloat, covers the vast majority of "what did I tell people about X" cases.
    """
    if not query.strip():
        return []
    full_query = f"in:sent newer_than:90d {query.strip()}"
    return _search_emails(full_query, limit)


def search_inbox_emails(query: str, limit: int = 5) -> List[Dict[str, Any]]:
    """Search the teacher's inbox from the last 90 days — same scope rules as sent."""
    if not query.strip():
        return []
    full_query = f"in:inbox newer_than:90d {query.strip()}"
    return _search_emails(full_query, limit)


def get_full_email(message_id: str) -> Dict[str, Any] | None:
    """
    Fetch one specific message by id with its full body. Used when Marimba
    finds a candidate via search and wants to dig deeper before answering.
    Returns the same shape as search results so the model sees a uniform schema.
    """
    service = _get_gmail_service()
    if not service:
        return None
    try:
        detail = (
            service.users()
            .messages()
            .get(userId="me", id=message_id, format="full")
            .execute()
        )
        headers = detail["payload"].get("headers", [])
        def _h(name: str) -> str:
            return next(
                (h["value"] for h in headers if h["name"].lower() == name.lower()),
                "",
            )
        body = _extract_body(detail.get("payload", {}))
        from datetime import datetime as _dt, timezone as _tz
        try:
            iso = _dt.fromtimestamp(
                int(detail.get("internalDate", "0")) / 1000, tz=_tz.utc
            ).isoformat()
        except Exception:
            iso = ""
        return {
            "id": message_id,
            "thread_id": detail.get("threadId", message_id),
            "subject": _h("Subject") or "(no subject)",
            "from": _h("From"),
            "to": _h("To"),
            "date": iso,
            "body": body or detail.get("snippet", ""),
        }
    except Exception as error:
        print(f"[Gmail get_full_email] error: {error}")
        return None


def fetch_email_detail(message_id: str) -> Dict[str, Any] | None:
    """
    Pull the full body + threading headers for a single message we already
    know about. Used to lazy-backfill emails that were ingested before the
    body / thread_id / rfc822_message_id columns existed.
    """
    service = _get_gmail_service()
    if not service:
        return None

    try:
        message_detail = (
            service.users()
            .messages()
            .get(userId="me", id=message_id, format="full")
            .execute()
        )
        headers = message_detail["payload"].get("headers", [])
        rfc822_id = next(
            (h["value"] for h in headers if h["name"].lower() == "message-id"), ""
        )
        cc_raw = ", ".join(
            h["value"] for h in headers if h["name"].lower() == "cc"
        )
        body = _extract_body(message_detail.get("payload", {}))
        return {
            "body": body,
            "thread_id": message_detail.get("threadId", ""),
            "rfc822_message_id": rfc822_id,
            "cc": cc_raw,
        }
    except HttpError as error:
        print(f"[Gmail Connector] Could not fetch message {message_id}: {error}")
        return None


def get_tasks() -> List[Dict[str, Any]]:
    """
    Standard interface function if we wanted to map emails directly to tasks.
    However, Email triage is handled specifically by triage_batch.
    """
    return []


if __name__ == "__main__":
    # Simple test sequence if run directly
    if is_configured():
        emails = fetch_unread_emails()
        print(f"✅ Extracted {len(emails)} unread emails.")
        for e in emails:
            print(f"- {e.subject} (From: {e.sender})")
    else:
        print("❌ Gmail is not configured. Run auth_gmail.py first.")
