"""
Connector: Gmail
Status: Active (Native)
Uses the local token.json generated by auth_gmail.py to read unread emails directly,
replacing the need for n8n.
"""

import base64
import email as email_lib
import os
import sys
from typing import Any, Dict, List

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from email_processor import IncomingEmail

# Paths relative to backend root
TOKEN_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "token.json")
SCOPES = [
    "https://www.googleapis.com/auth/gmail.modify",
    "https://www.googleapis.com/auth/gmail.send",
]


def is_configured() -> bool:
    """Returns True if the OAuth token is present and valid."""
    return os.path.exists(TOKEN_FILE)


def _get_gmail_service():
    """Builds and returns the Gmail API service object, refreshing the token if needed."""
    if not is_configured():
        return None

    try:
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

        if creds.expired and creds.refresh_token:
            from google.auth.transport.requests import Request
            creds.refresh(Request())
            # Persist the refreshed token so the next call doesn't need to refresh again
            with open(TOKEN_FILE, "w") as f:
                f.write(creds.to_json())

        service = build("gmail", "v1", credentials=creds)
        return service
    except Exception as e:
        print(f"Error building Gmail service: {e}")
        return None


LABEL_NAME = "marimba-processed"


def _extract_body(payload: Dict[str, Any]) -> str:
    """
    Walk a Gmail message payload and return the best plain-text body we can find.

    Gmail can deliver simple single-part messages or multipart trees (text/plain
    + text/html + attachments). We prefer text/plain; if none exists we fall
    back to text/html stripped to bare text. Returns "" if nothing usable.
    """
    import re

    def _decode(data: str) -> str:
        try:
            return base64.urlsafe_b64decode(data.encode("ASCII")).decode("utf-8", errors="replace")
        except Exception:
            return ""

    def _walk(node: Dict[str, Any]) -> tuple[str, str]:
        """Returns (plain_text, html_text) found anywhere in this node."""
        plain, html = "", ""
        mime = node.get("mimeType", "")
        body = node.get("body", {})
        data = body.get("data")
        if data:
            decoded = _decode(data)
            if mime == "text/plain":
                plain += decoded
            elif mime == "text/html":
                html += decoded
        for part in node.get("parts", []) or []:
            p, h = _walk(part)
            plain += p
            html += h
        return plain, html

    plain, html = _walk(payload or {})
    if plain.strip():
        return plain.strip()
    if html.strip():
        # crude HTML → text fallback (good enough for replying with context)
        stripped = re.sub(r"<[^>]+>", "", html)
        stripped = re.sub(r"\s+\n", "\n", stripped)
        return stripped.strip()
    return ""


def get_or_create_label(service) -> str:
    """Finds the 'marimba-processed' label ID, or creates it if it doesn't exist."""
    results = service.users().labels().list(userId="me").execute()
    labels = results.get("labels", [])
    for label in labels:
        if label["name"] == LABEL_NAME:
            return label["id"]

    # Create it if not found
    label_object = {
        "name": LABEL_NAME,
        "labelListVisibility": "labelShow",
        "messageListVisibility": "show",
        "color": {
            "backgroundColor": "#ffad46",  # Amber color
            "textColor": "#000000",
        },
    }
    created_label = (
        service.users().labels().create(userId="me", body=label_object).execute()
    )
    return created_label["id"]


def fetch_unread_emails() -> List[IncomingEmail]:
    """
    Fetches emails from the last 5 days that haven't been processed by Marimba yet.
    Formats them exactly as n8n used to, so email_processor.py can naturally parse them.
    As soon as they are fetched, they are labeled 'marimba-processed' in Gmail.
    """
    service = _get_gmail_service()
    if not service:
        return []

    try:
        label_id = get_or_create_label(service)

        # 1. Fetch messages in inbox not yet processed by Marimba from the last 5 days
        query = f"in:inbox -label:{LABEL_NAME} newer_than:5d"
        results = service.users().messages().list(userId="me", q=query).execute()
        messages = results.get("messages", [])

        if not messages:
            return []

        parsed_emails = []
        messages_to_label = []

        # 2. Fetch full message details for each ID
        for msg in messages:
            msg_id = msg["id"]
            message_detail = (
                service.users()
                .messages()
                .get(userId="me", id=msg_id, format="full")
                .execute()
            )

            headers = message_detail["payload"].get("headers", [])
            subject = next(
                (h["value"] for h in headers if h["name"] == "Subject"), "No Subject"
            )
            sender = next(
                (h["value"] for h in headers if h["name"] == "From"), "Unknown Sender"
            )
            recipient = next((h["value"] for h in headers if h["name"] == "To"), "")
            # RFC822 Message-ID — the canonical id used for In-Reply-To / References
            # so replies thread inside the original Gmail conversation.
            rfc822_id = next(
                (h["value"] for h in headers if h["name"].lower() == "message-id"), ""
            )

            snippet = message_detail.get("snippet", "")
            body = _extract_body(message_detail.get("payload", {}))

            incoming_email_data = {
                "id": msg_id,
                "threadId": message_detail.get("threadId", msg_id),
                "snippet": snippet,
                "body": body,
                "rfc822_message_id": rfc822_id,
                "internalDate": message_detail.get("internalDate", "0"),
                "Subject": subject,
                "From": sender,
                "To": recipient,
                "payload": {
                    "mimeType": message_detail["payload"].get("mimeType", "text/plain")
                },
                "labels": [],
            }

            try:
                validated_email = IncomingEmail(**incoming_email_data)
                parsed_emails.append(validated_email)
                messages_to_label.append(msg_id)
            except Exception as e:
                print(f"Error parsing email {msg_id}: {e}")

        # 3. Label all successfully fetched emails as 'marimba-processed'
        if messages_to_label:
            service.users().messages().batchModify(
                userId="me",
                body={
                    "ids": messages_to_label,
                    "addLabelIds": [label_id],
                    # We no longer remove 'UNREAD' here, so you maintain your personal unread status!
                },
            ).execute()
            print(
                f"[Gmail Connector] Fetched and tagged {len(messages_to_label)} emails as '{LABEL_NAME}'."
            )

        return parsed_emails

    except HttpError as error:
        print(f"An error occurred pulling emails: {error}")
        return []


def send_email(to: str, subject: str, body: str) -> bool:
    """
    Send an email from the authenticated Gmail account.

    Args:
        to: Recipient email address
        subject: Email subject line
        body: Plain-text email body

    Returns:
        True if sent successfully, False otherwise
    """
    service = _get_gmail_service()
    if not service:
        return False

    try:
        message = email_lib.message.EmailMessage()
        message["To"] = to
        message["Subject"] = subject
        message.set_content(body)

        encoded = base64.urlsafe_b64encode(message.as_bytes()).decode()
        service.users().messages().send(
            userId="me", body={"raw": encoded}
        ).execute()
        return True

    except Exception as error:
        print(f"[Gmail Connector] Error sending email: {error}")
        return False


def send_reply(
    *,
    to: str,
    subject: str,
    body: str,
    in_reply_to_rfc822_id: str,
    thread_id: str | None,
) -> bool:
    """
    Send a threaded reply. The message lands inside the same Gmail
    conversation as the original on both sender's and recipient's sides.

    Threading is achieved by:
      - Setting In-Reply-To and References to the RFC822 Message-ID of the
        message being replied to (RFC 2822 standard — the mail client uses
        this to group messages into threads).
      - Passing threadId in the Gmail API send payload so Gmail itself
        keeps it inside the originating thread on our account.

    Subject is normalised to "Re: ..." if not already prefixed.
    """
    service = _get_gmail_service()
    if not service:
        return False

    if not subject.lower().startswith("re:"):
        subject = f"Re: {subject}"

    try:
        message = email_lib.message.EmailMessage()
        message["To"] = to
        message["Subject"] = subject
        if in_reply_to_rfc822_id:
            message["In-Reply-To"] = in_reply_to_rfc822_id
            message["References"] = in_reply_to_rfc822_id
        message.set_content(body)

        encoded = base64.urlsafe_b64encode(message.as_bytes()).decode()
        payload: Dict[str, Any] = {"raw": encoded}
        if thread_id:
            payload["threadId"] = thread_id

        service.users().messages().send(userId="me", body=payload).execute()
        return True

    except Exception as error:
        print(f"[Gmail Connector] Error sending threaded reply: {error}")
        return False


def fetch_email_detail(message_id: str) -> Dict[str, Any] | None:
    """
    Pull the full body + threading headers for a single message we already
    know about. Used to lazy-backfill emails that were ingested before the
    body / thread_id / rfc822_message_id columns existed.
    """
    service = _get_gmail_service()
    if not service:
        return None

    try:
        message_detail = (
            service.users()
            .messages()
            .get(userId="me", id=message_id, format="full")
            .execute()
        )
        headers = message_detail["payload"].get("headers", [])
        rfc822_id = next(
            (h["value"] for h in headers if h["name"].lower() == "message-id"), ""
        )
        body = _extract_body(message_detail.get("payload", {}))
        return {
            "body": body,
            "thread_id": message_detail.get("threadId", ""),
            "rfc822_message_id": rfc822_id,
        }
    except HttpError as error:
        print(f"[Gmail Connector] Could not fetch message {message_id}: {error}")
        return None


def get_tasks() -> List[Dict[str, Any]]:
    """
    Standard interface function if we wanted to map emails directly to tasks.
    However, Email triage is handled specifically by triage_batch.
    """
    return []


if __name__ == "__main__":
    # Simple test sequence if run directly
    if is_configured():
        emails = fetch_unread_emails()
        print(f"✅ Extracted {len(emails)} unread emails.")
        for e in emails:
            print(f"- {e.subject} (From: {e.sender})")
    else:
        print("❌ Gmail is not configured. Run auth_gmail.py first.")
